### ISSUE TITLE
Mark Course Note Git Repo of Emad-Sadeghi

### ISSUE THREAD

**Issue by emadsadeghi** [emadsadeghi/STAT679Notes#1]
@cecileane @coraallencoleman 

https://github.com/emadsadeghi/STAT679Notes/commit/84aa1b89b7462143df17629f2c18442b2817d7c1

In class so far, I have found the command `grep` to be very useful. I learned that with the flag `--color` after the `grep` command I can see a color-coded version of the word that I'd like to find. 

For example, the code below searches every where for the word "emad" occurs in the files in the  **/etc/passwd** folder, with all the matches colored 🔴 . 

`grep --color emad /etc/passwd`

---
### Tutorials on Grep:
Also, in doing homework 1 exercise 2, I found the following three tutorials very useful:  

| Rank        | Links           |
| ------------- |:-------------:| 
| 👍 **1**     | [First Link ](https://ryanstutorials.net/linuxtutorial/grep.php)  | 
| 👍 👍 :**2**      | [Second Link ](https://danielmiessler.com/study/grep/)       | 
| 👍 👍 👍 :**3** | [Third Link ](https://www.youtube.com/watch?v=ckzN9P9zBhM)    |

---

**Comment by cecileane** [comment]
so cool! thanks Emad.
