### ISSUE TITLE
Mark Sed Exercise of Emad-Sadeghi 

### ISSUE THREAD

**Issue by emadsadeghi** [emadsadeghi/STAT679Notes#2]
@cecileane @coraallencoleman 

https://github.com/emadsadeghi/STAT679Notes/commit/f208b3a79f255652a1fe3b2d54ee393a9556eaea 

In the directory called `/STAT679Notes`, please run the script "sed_exercise.sh" as follows:  

`./sed_exercise.sh`. 

### There are two lines of code in the script: 
1.  The first line of code changes every value in the "Minimum" column to eliminate the commas inside the numbers and the quotes around the numbers. The results are dumped in the file called "new_tableofSNPs.csv".
---
`cat tableofSNPs.csv | gsed -E 's/\"([0-9]+),([0-9]+)\"/\1\2/g' | gsed -E 's/\"([0-9]+),([0-9]+),([0-9]+)\"/\1\2\3/g' > new_tableofSNPs.csv`

---
2.  The second line of code checks if the new CSV "new_tableofSNPs.csv" file is correct.
---
`cat new_tableofSNPs.csv | gsed -E 's/[^,]//g' | grep -xv ",,," | wc -l`

---
This line returns the number of lines that do not have exactly three commas. Running this line on the new CSV file will output 0, which means that all rows have exactly three commas.

**Comment by cecileane** [comment]
very cool!

you don't need cat really: just `gsed ...options... filename | other command`
